dist: bionic  # ubuntu 18.04
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

env: UBUNTU_VERSION=ubuntu1804

before_script:
  - yapf -p -r -d --style='{COLUMN_LIMIT:80}' ./
  - isort -rc -w 80 -d ./
  - autoflake -r ./

after_success:
  - coverage report
